# 网页标题
site_name: Python技术文档库
# 站点url
site_url: https://Gearless01Joe.github.io/Markdown_test/
# 导航标题
nav:
  - 首页: index.md
  - 关于更新: update.md
  # - 关于: about.md
  - 国自然选题推荐数据清洗: api.md
  # - RCSB PDB: RCSB_PDB.md

# 插件
plugins:
     - search
     - mkdocstrings:
         default_handler: python
         handlers:
           python:
             paths: [../src]        # 指向你的源码目录
             options:
               docstring_style: google    # 你的 docstring 风格（google/napoleon/numpy）
               show_source: true

# 主题，目前预选：readthedocs、material
theme: material